/**
 * Created by kinnimew on 6/8/15.
 */

var config = require('../config');

var fs = require('fs');
var webshooter = require('../webshooter.js');
var expect = require('Chai').expect;
var dateFormat = require('dateformat');

var now = dateFormat('yyyymmddHHMM');
var outputFilePath = 'screenshots/' + now + '.png';

describe('Screenshot', function () {
    it('should save screenshot of ' + config.url + ' to ' + outputFilePath + '.', function (done) {
        webshooter.takeScreenshot(config.url, outputFilePath, function (err) {

            expect(err).to.be.null;

            fs.exists(outputFilePath, function (exists) {
                expect(exists).to.be.true;
                done();
            });
        });
    });
});

describe('Email Notification', function () {

    var startTime = new Date();

    it('should send an email to ' + config.recipients + ' with attachment ' + (now + ".png"), function (done) {

        var endTime = new Date();

        var email = {
            to: config.recipients,
            subject: "Webshooter - " + config.url,
            text: "This email is generated by Webshooter\n Elapsed Time = " + (endTime - startTime) + "ms",
            attachment: [
                {path: outputFilePath, name: now + ".png"}
            ]
        };

        webshooter.send(email, function (err, message) {

            expect(err).to.be.null;
            expect(message).to.be.not.empty;
            done();
        });

    });

    after(function () {
        fs.exists(outputFilePath, function (exists) {
            if (exists) {
                fs.unlinkSync(outputFilePath);
            }
        });
    });
});